### ISSUE TITLE
Underscore 1.2.3 Mixin not working

### ISSUE THREAD

**Issue by chrispaterson** [wookiehangover/underscore.deferred#9]
Use case:

var _ = require('underscore')._;

module.exports = function() {
   _.mixin( require('underscore.deferred') );
   var dfd = new _.Deferred();
}
RESULT: Error Message "undefined is not a function"

It still works independently of underscore, just won't mixin.

**Comment by tbranyen** [comment]
Underscore was recently changed, have you tried

``` javascript
var _ = require("underscore");
```

**Comment by chrispaterson** [comment]
Just tried that and it is the same result.

**Comment by wookiehangover** [comment]
thanks for opening an issue! this was happening because of how we were detecting the presence of `module`. This is fixed as of v0.1.2, which is on the npm registry now.
